#!/bin/sh
set -e

WORKDIR=`mktemp -d`
trap "rm -rf $WORKDIR" 0 INT QUIT ABRT PIPE TERM
cd $WORKDIR
cat <<EOF >buildtest.c
#include <stdio.h>

#include <pinyin.h>

int main()
{
    pinyin_context_t *ctx = pinyin_init(SYSTEMDIR "/data", USERDIR);
    if (!ctx) {
        fprintf(stderr, "pinyin_init() fails.\n");
        return -1;
    }
    pinyin_fini(ctx);
    return 0;
}
EOF

touch $WORKDIR/user.conf

g++ -o buildtest buildtest.c \
    `pkg-config --cflags --libs libpinyin` \
    -DSYSTEMDIR="\"`pkg-config --variable=pkgdatadir libpinyin`\"" \
    -DUSERDIR="\"$WORKDIR\""
./buildtest
